### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by Ksengine** [eng-tools/sfsidb#1]
SignalPy updated.
Bugs fixed and now it's super.
Update your project to signalpy  1.0.4
**I am the author of SignalPy**
I can help you to improve this project.
can you help me to improve signalpy
i made it for another use.
i did'nt hope that is is used by anyone.
Thank you for using SignalPy

**Comment by millen1m** [comment]
Unfortunately, this project has been deprecated in favor of the sfsimodels package and the signalpy package was another private package that has also been deprecated. Best wishes with your development.
